# Delete these routes and define your own shop routes here

webgriffe_sylius_clerk_static_welcome:
    path: /static-welcome/{name}
    defaults:
        _controller: WebgriffeSyliusClerkPlugin:Greeting:staticallyGreet
        name: ~

webgriffe_sylius_clerk_dynamic_welcome:
    path: /dynamic-welcome/{name}
    defaults:
        _controller: WebgriffeSyliusClerkPlugin:Greeting:dynamicallyGreet
        name: ~
